### ISSUE TITLE
Implement E2E test

### ISSUE THREAD

**Issue by chowaniecpiotr** [wildhamsters/battleships#166]
Implement end-2-end test using Selenium.

Must:
- [x] Login a player on different browsers
- [x] Enter the game by both players
- [x] Random shots of both players until game isn't finished
- [x] Assertion whether any player wins

Could:
- [ ] Logout both players after the game has finished
- [ ] Player registration
- [ ] Running 2 games at the same time

**Comment by KamKoz92** [comment]
Closed with #167
